# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cubic.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Brain.AIBrain import ReplyBrain
from PyQt5 import QtCore, QtGui, QtWidgets
import os
import threading
import sys
from PyQt5.QtGui import QColor
import speech_recognition as sr
from googletrans import Translator
import pyttsx3



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1917, 1068)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1921, 1071))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\NEW\\OneDrive\\Documents\\Ai\\Template for AI\\Jarvis\\GUI materials\\connections.gif"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1720, 980, 191, 51))
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"background-color: rgb(58, 0, 88);\n"
"    border-color: rgb(65, 65, 65);\n"
"  border-radius:5px ;\n"
"   color:rgba(255, 255, 255, 200);\n"
"    font: 63 10pt Bahnschrift SemiBold SemiConden;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"  background-color:rgba(255, 107, 107, 255);\n"
"   padding-left:5px;\n"
"   padding-top:5px;\n"
"   background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"  background-color: rgb(121, 121, 121);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1510, 980, 191, 51))
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{\n"
"background-color: rgb(93, 0, 140);\n"
"    border-color: rgb(65, 65, 65);\n"
"  border-radius:5px ;\n"
"   color:rgba(255, 255, 255, 200);\n"
"    font: 63 10pt Bahnschrift SemiBold SemiConden;\n"
"}\n"
"QPushButton#pushButton_2:pressed{\n"
"  background-color:rgba(255, 107, 107, 255);\n"
"   padding-left:5px;\n"
"   padding-top:5px;\n"
"   background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#pushButton_2:hover{\n"
"  background-color: rgb(121, 121, 121);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(0, 0, 431, 1071))
        self.plainTextEdit.setStyleSheet("background-color: rgb(50, 0, 75);\n"
"border-right-color: rgb(255, 255, 255);\n"
"border-left-color: rgb(255, 255, 255);\n"
"font: 63 10pt Bahnschrift SemiBold SemiConden;\n"
"   color:rgba(255, 255, 255, 200);\n")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1650, 170, 251, 51))
        self.pushButton_3.setStyleSheet("QPushButton#pushButton_3{\n"
"background-color: rgb(93, 0, 140);\n"
"    border-color: rgb(65, 65, 65);\n"
"  border-radius:5px ;\n"
"   color:rgba(255, 255, 255, 200);\n"
"    font: 63 10pt Bahnschrift SemiBold SemiConden;\n"
"}\n"
"QPushButton#pushButton_3:pressed{\n"
"  background-color:rgba(255, 107, 107, 255);\n"
"   padding-left:5px;\n"
"   padding-top:5px;\n"
"   background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#pushButton_3:hover{\n"
"  background-color: rgb(121, 121, 121);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton4.setGeometry(QtCore.QRect(1650, 260, 251, 51))
        self.pushButton4.setStyleSheet("QPushButton#pushButton4{\n"
"background-color: rgb(58, 0, 88);\n"
"    border-color: rgb(65, 65, 65);\n"
"  border-radius:5px ;\n"
"   color:rgba(255, 255, 255, 200);\n"
"    font: 63 10pt Bahnschrift SemiBold SemiConden;\n"
"}\n"
"QPushButton#pushButton4:pressed{\n"
"  background-color:rgba(255, 107, 107, 255);\n"
"   padding-left:5px;\n"
"   padding-top:5px;\n"
"   background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#pushButton4:hover{\n"
"  background-color: rgb(121, 121, 121);\n"
"}")
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1650, 350, 251, 51))
        self.pushButton_5.setStyleSheet("QPushButton#pushButton_5{\n"
"background-color: rgb(93, 0, 140);\n"
"    border-color: rgb(65, 65, 65);\n"
"  border-radius:5px ;\n"
"   color:rgba(255, 255, 255, 200);\n"
"    font: 63 10pt Bahnschrift SemiBold SemiConden;\n"
"}\n"
"QPushButton#pushButton_5:pressed{\n"
"  background-color:rgba(255, 107, 107, 255);\n"
"   padding-left:5px;\n"
"   padding-top:5px;\n"
"   background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#pushButton_5:hover{\n"
"  background-color: rgb(121, 121, 121);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton6.setGeometry(QtCore.QRect(1650, 440, 251, 51))
        self.pushButton6.setStyleSheet("QPushButton#pushButton6{\n"
"background-color: rgb(58, 0, 88);\n"
"    border-color: rgb(65, 65, 65);\n"
"  border-radius:5px ;\n"
"   color:rgba(255, 255, 255, 200);\n"
"    font: 63 10pt Bahnschrift SemiBold SemiConden;\n"
"}\n"
"QPushButton#pushButton6:pressed{\n"
"  background-color:rgba(255, 107, 107, 255);\n"
"   padding-left:5px;\n"
"   padding-top:5px;\n"
"   background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#pushButton6:hover{\n"
"  background-color: rgb(121, 121, 121);\n"
"}")
        self.pushButton6.setObjectName("pushButton6")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1230, 360, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1700, 90, 221, 41))
        self.label_3.setStyleSheet("    font: 63 20pt Bahnschrift SemiBold SemiConden;\n"
"\n"
"text-decoration: underline;\n"
"color: rgb(170, 170, 255);\n"
"color: rgb(242, 216, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(873, 90, 251, 61))
        self.label_4.setStyleSheet("    font: 63 40pt Bahnschrift SemiBold SemiConden;\n"
"\n"
"text-decoration: underline;\n"
"color: rgb(170, 170, 255);\n"
"color: rgb(242, 216, 255);")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "STOP"))
        self.pushButton_2.setText(_translate("MainWindow", "START"))
        self.pushButton_3.setText(_translate("MainWindow", "TRIP GUIDE"))
        self.pushButton4.setText(_translate("MainWindow", "NUMBER SCANNER"))
        self.pushButton_5.setText(_translate("MainWindow", "CARBON CALCULATOR"))
        self.pushButton6.setText(_translate("MainWindow", "ANNOYER"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "Applications"))
        self.label_4.setText(_translate("MainWindow", "CU  BIC"))
        self.pushButton_2.clicked.connect(self.start)

    def set_text_color(plain_text_edit, color):
        # Create a text cursor and set the font color using a QTextCharFormat
        text_cursor = plain_text_edit.textCursor()
        text_format = QtGui.QTextCharFormat()
        text_format.setForeground(QColor(color))
        text_cursor.mergeCharFormat(text_format)
        plain_text_edit.setCurrentCharFormat(text_format)

    def Listen(self):
        r = sr.Recognizer()
        with sr.Microphone() as source:
            T = ('''
Listening...''')
            print("/")
            QtCore.QMetaObject.invokeMethod(self.plainTextEdit, 'appendPlainText', QtCore.Qt.QueuedConnection, QtCore.Q_ARG(str, T))

            r.pause_threshold = 0.5
            audio = r.listen(source,0,8) # Listening Mode.....
        try:
            R = ('''
Recognizing...''')
            QtCore.QMetaObject.invokeMethod(self.plainTextEdit, 'appendPlainText',QtCore.Qt.QueuedConnection, QtCore.Q_ARG(str, R))

            print("..")
            query = r.recognize_google(audio,language="en")
        except:
            return ""
        query = str(query).lower()
        return query

    def TranslationHinToEng(self,Text):
        query = self.Listen()
        data = self.TranslationHinToEng(query)
        return data

    def start(self):
        line = str(Text)
        translate = Translator()
        result = translate.translate(line)
        data = result.text
        return data

    def MicExecution(self):
        movie = QtGui.QMovie("C:\\Users\\NEW\\OneDrive\\Documents\\Ai\\Template for AI\\Jarvis\\GUI materials\\connections.gif")
        self.label.setMovie(movie)
        movie.start()
        # Start the speech processing thread
        speech_thread = threading.Thread(target=self.process_speech)
        speech_thread.start()

    def process_speech(self):

        while True:

            Data = self.MicExecution()
            Data1 = str(Data).replace(".", "")
            Reply = ReplyBrain(Data1)
            TrueReply = f"\nYou : {Data} \n\nCubic : {Reply}"
            engine = pyttsx3.init("sapi5")
            voices = engine.getProperty('voices')
            engine.setProperty('voices', voices[1].id)
            engine.setProperty('rate', 170)
            # Update the text box with the reply
            QtCore.QMetaObject.invokeMethod(self.plainTextEdit, 'appendPlainText', QtCore.Qt.QueuedConnection, QtCore.Q_ARG(str, TrueReply))

            engine.say(f"{Reply}")
            engine.runAndWait()

    def start_jarvis(self):
        speech_thread = threading.Thread(target=self.process_speech)
        speech_thread.start()


class Gui_Start(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.jarvis_ui = Ui_MainWindow()
        self.jarvis_ui.setupUi(self)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = Gui_Start()
    MainWindow.show()
    sys.exit(app.exec_())

